# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160810_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('difficult', 'difficult'), ('none', 'none of your business')], default='none', max_length=20),
        ),
    ]
